name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-and-analyze:
    name: Unit Test & Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        run: mvn test

  build-and-publish-snapshot:
    name: Build & Publish Snapshot
    if: github.ref == 'refs/heads/develop'
    needs: test-and-analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build package (skip tests)
        run: mvn package -DskipTests

      - name: Publish Snapshot to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}