name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        permissions:
          contents: read
          packages: write
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
        with:
          release-branch-name: "main"
          git-release-bot-name: "cal-bot"
          git-release-bot-email: "calpangdev@gmail.com"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          # release
          maven-repo-server-id: "github"
          maven-repo-server-username: ${{ github.actor }}
          maven-repo-server-password: ${{ secrets.GITHUB_TOKEN }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs"

#          gpg-enabled: true
#          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
#          gpg-key: ${{ secrets.GPG_KEY }}


